version: '3.3'

volumes:
  db_value:
  static_value:

services:
  db:
    image: alpine:latest
    volumes:
      - sqlite_data:/var/lib/sqlite3/db/
  # db:
  #   image: postgres:13
  #   volumes:
  #     - db_value:/var/lib/postgresql/data/
  #   env_file:
  #     - .env
    restart: always

  achievements:
    image: rv369/achievements_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: rv369/achievements_nginx:latest
    env_file: 
      - .env
    ports:
      - "8000:80"
    volumes:
      - static_value:/var/html/static/
    depends_on:
      - achievements
    restart: always
