# Generated by Django 3.2.3 on 2024-03-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name_achievements', models.CharField(max_length=200)),
                ('number_of_points', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AchievementPerson',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'achievement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.achievement',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('person_name', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(max_length=200)),
                (
                    'achievements',
                    models.ManyToManyField(
                        related_name='achievements_person',
                        through='api.AchievementPerson',
                        to='api.Achievement',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='achievementperson',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api.person'
            ),
        ),
        migrations.AddField(
            model_name='achievement',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='person',
                to='api.person',
            ),
        ),
    ]
