# Generated by Django 3.2.3 on 2024-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='name_achievements',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
